### ISSUE TITLE
how to properly combine selector and sortFunction options 

### ISSUE THREAD

**Issue by abubelinha** [Sjeiti/TinySort#144] opened 2018-07-04 11:18 UTC
This comes from https://github.com/Sjeiti/TinySort/issues/132 , but I think it might deserve a new issue title, since the sortFunction mentioned there does already work.
My problem comes only when I try to combine the **selector** and **sortFunction** options altogether.

The jsfiddles below reproduces the aforementioned "sort by text length" function.
For some reason, the "sort by length" button is failing when I am trying to use it to sort a list using a span as selector. **Has the following tinysort() call an incorrect syntax?**

```
<div id=mydiv>
   <ol>
      <li><span>1</span> <span class=myclass>abcde</span></li>
      <li><span>2</span> <span class=myclass>bcde</span></li>
      <li><span>3</span> <span class=myclass>zyx</span></li>
      <li><span>4</span> <span class=myclass>z</span></li>
   </ol>
</div>

<script type=text/javascript>
function sortByLength(a,b) {
   var lena = a.elm.textContent.length
   var lenb = b.elm.textContent.length;
   return lena === lenb ? 0 : ( lena>lenb ? 1 : -1);
}
tinysort("div#mydiv>ol>li", {selector:'span.myclass', sortFunction: sortByLength});
</script>
```
I would expect the list to be sorted upside-down after the tinysort() call, based on the string lengths inside the right spans ... but when I try to call this from the "sort by length" button in my jsfiddle, it does not work:

Please note the jsfiddle also needs **charorder plugin** to be used in another button. So I tried to test differences in loading or not loading that plugin, although it shouldn't change the behaviour of the "sort by length button" (since the tinysort call in it does not use charorder):
- With charorder loaded, "sort by length" button does not work.
https://jsfiddle.net/abubelinha/kcfpu3sr/161/
- Without charorder, "sort by length" does sort but not as I would expect from the provided sortFunction 
https://jsfiddle.net/abubelinha/kcfpu3sr/162/

**Comment by Sjeiti** [comment] 2018-07-05 06:57
Verified bug http://jsfiddle.net/Sjeiti/cfoqtk7z/
duplicate of #122

**Closed by Sjeiti** 2018-07-05 06:57 UTC
Labels: bug, duplicate

**Comment by abubelinha** [comment] 2018-07-10 22:11
Thanks @Sjeiti , but that bug does not explain why the 2nd jsffidle above fails:  it does NOT use charOrder script. 

I made a much simpler version showing just the button which fails running the sortFunction option:
https://jsfiddle.net/abubelinha/ovr6cn21/

What is failing there?

**Comment by Sjeiti** [comment] 2018-07-12 07:51
You expect the custom sort function to sort a subselection when in fact it sorts the length of the entire list-element. The custom sort function ignores all other properties you set because it expects you to implement these yourself. This is by design.
But I'll update the documentation to note that all other properties will be ignored.

**Comment by Sjeiti** [comment] 2018-07-14 07:53
Still working on that last one, I did fix one charorder issue but there is still one thing wrong

**Comment by abubelinha** [comment] 2018-07-15 12:11
Thanks @Sjeiti 
Does that bug have an open issue link which I can follow?
I am not sure where I should look at: this issue and the other you linked to are already closed.

**Comment by Sjeiti** [comment] 2018-07-16 20:59
@abubelinha I don't have time to look into it this week but when I do I'll refer you when it's fixed.

As for your question regarding passing params: there is one open pull request touching that issue. I don't think I'll merge it as is, but I might extend the sortFunction with similar functionality... maybe...

**Comment by abubelinha** [comment] 2020-08-14 18:12
> @abubelinha I don't have time to look into it this week but when I do I'll refer you when it's fixed.

Any advances?  I recall the status of my question: **custom sort functions failed when charOrder plugin was loaded**. 
As I see a later (but also old) [#153 issue related to charOrder plugin](https://github.com/Sjeiti/TinySort/issues/153), now I wonder if that is related to my issue.

Or perhaps mine was simply a collateral effect of what you said [above](https://github.com/Sjeiti/TinySort/issues/144#issuecomment-404422302) about sortFunction? (so any _sortFunction_ will ignore _charOrder_ "by design", and not due to a fail in any of them):

> The custom sort function ignores all other properties you set because it expects you to implement these yourself. This is by design.

----------------
And what about this other pending question? You mentioned a related pull request (I don't know the link):

> As for your question regarding passing params: there is one open pull request touching that issue. I don't think I'll merge it as is, but I might extend the sortFunction with similar functionality... maybe...

I am specially interested in this, because a custom sortFunction can also be used to somehow resemble the failing charOrder plugin (at least in the mean time, if the issues above still persist).

For example, I have now a custom _myAZcharOrderFunction()_ which works perfectly with TinySort for sorting elements based on their inner text (a.elm.textContent vs b.elm.textContent).
So I can't reuse the same function for sorting elements based on their _title_ attribute, for example (I would need to create a different function):

It works great like this: 
`tinysort('div.mynames>span.name', {sortFunction: myAZcharorderFunction});`

But this wouldn't work: 
`tinysort('div.mynames>span.name', {attr:'title', sortFunction: myAZcharOrderFunction});`
`tinysort('div.mynames>span.name', {attr:'title'}, {sortFunction: myAZcharOrderFunction});`

BTW ... which one would be the correct one of the last two calls? I guess the 1st one, but I still have not a clear understanding of when using separate curly brackets. [This example](https://github.com/Sjeiti/TinySort#multiple-sort-criteria) confuses me a bit:

`tinysort('ul#xmul>li','span.name',{selector:'span.date',data:'timestamp'});
`
... would these make any different effect?

```
tinysort('ul#xmul>li',{selector:'span.name'},{selector:'span.date'},{data:'timestamp'});
tinysort('ul#xmul>li',{selector:'span.name',selector:'span.date'},{data:'timestamp'});
tinysort('ul#xmul>li',{selector:'span.name',selector:'span.date',data:'timestamp'});

```

**Comment by abubelinha** [comment] 2024-09-15 18:59
> As for your question regarding passing params: there is one open pull request touching that issue. I don't think I'll merge it as is, but I might extend the sortFunction with similar functionality

@Sjeiti have you any solution for passing parameters (i.e. a selector) to sortFunction?

My example in https://jsfiddle.net/abubelinha/ovr6cn21/35/ can sort elements based on a given selector, but its name has to be hardcoded inside the custom function and that is not a general solution.
